### ISSUE TITLE
Change Github page url

### ISSUE THREAD

**Issue by fenditsim** [EuroGraphicsUK/eguk-website-code#2]
We could change the url of our website from

> https://eurographicsuk.github.io/eguk-website-code/

to

> https://eurographicsuk.github.io/

I think the latter url is better. What do you think?

**Comment by kaidatavis** [comment]
I am trying this right now and it seems to break everything. Sorry about this. It seems that that the static files (html, css, etc.) need to in the root directory to work (currently they are in the 'dist' directory). I am trying to see if there is anyway to fix this.

In the end, it is not that important as we will use our custom domain eguk.org.uk, which links to the original GitHub Pages domain.

**Comment by kaidatavis** [comment]
I changed the url to all lower case and at least it can find the html file now, but the images are still missing. 

@fenditsim, can you rerun the astro code locally, so it regenerates the static files (html, css, etc.), and then push the new version to GitHub?

Currently I can see from the source code that it still uses file path like `https://eurographicsuk.github.io/eguk-website-code/_astro/favicon.vp_fBu0c.svg`, which won't work after the repository name change.

**Comment by kaidatavis** [comment]
@fenditsim, when you regenerate the static files, can you also try changing the output folder to `docs` (instead of `dist`)? Currently the GitHub Pages is set up to load the files from the `docs` folder (the other option is root, which may be less ideal).

**Comment by fenditsim** [comment]
> I am trying this right now and it seems to break everything. Sorry about this. It seems that that the static files (html, css, etc.) need to in the root directory to work (currently they are in the 'dist' directory). I am trying to see if there is anyway to fix this.
> 
> In the end, it is not that important as we will use our custom domain eguk.org.uk, which links to the original GitHub Pages domain.

I believe it has to do with modifying another script called `config.yaml` and run the build command again - I'm going to address them, as well as updating ReadME.md as soon as possible. Please wait for new changes

**Comment by fenditsim** [comment]
> I changed the url to all lower case and at least it can find the html file now, but the images are still missing.
> 
> @fenditsim, can you rerun the astro code locally, so it regenerates the static files (html, css, etc.), and then push the new version to GitHub?
> 
> Currently I can see from the source code that it still uses file path like `https://eurographicsuk.github.io/eguk-website-code/_astro/favicon.vp_fBu0c.svg`, which won't work after the repository name change.

The site is run normally after:
1. Removing lines that specify base path ('/eguk-website-code/') in both as `astro.config.mjs` and `config.yaml` (see commit f255d4c6ab2b238f547c7798445fec5f2cdc55c2)
2. Deploying our site via Github Actions (see commit 29318243129090956ca1d0fe27efac30099fdf38, 3203a8404023f24db9a76f72c0e6d8d124028902 and 0407169e751ac1c833788bf74a9d6a89a76d790d)

**Comment by fenditsim** [comment]
> @fenditsim, when you regenerate the static files, can you also try changing the output folder to `docs` (instead of `dist`)? Currently the GitHub Pages is set up to load the files from the `docs` folder (the other option is root, which may be less ideal).

In Astro documentation, they recommend deploy the site via Github actions (reference link: https://docs.astro.build/en/guides/deploy/github/). This requires a configuration of a Github Action (link: https://docs.astro.build/en/guides/deploy/github/#configure-a-github-action).

I tried to generate the new output in `docs` and `dist` (see commit 2fcc14e70371c7dcda876a61b232e063603dc8e5), but the site did not show css properly. Then I switched back to the method Astro recommends, and it worked.

Please have a look at the site and see if it works normally from your end - if yes I can close this issue.

**Comment by kaidatavis** [comment]
OK, let's use GitHub action as Astro recommended. In this case we don't need to output to the 'docs' folder, which is for the static deployment method.
