### ISSUE TITLE
Updating README.md

### ISSUE THREAD

**Issue by fenditsim** [EuroGraphicsUK/eguk-website-code#3]
README.md should include the following:
- setup and building the site, i.e., what needs to be installed, what comments to be run to build the site etc.
- how to update the content of a page

**Comment by kaidatavis** [comment]
Nice work. Would it be better to just run `npm install` instead of `npm install astro`? This will install the version of astro specified (currently 4.12.2?) and other package dependency if there is any.

**Comment by fenditsim** [comment]
Yes - both `npm install` and `npm install astro` work well.

`npm install` works well and quicker if certain files (such as package-lock.json) are in the directory. If, for some reasons, these files are not in the directory, then running `npm install astro` also does the same job (but a bit slower).

Thanks for the suggestion! I'm going to update that part.
